/*
 * EXTI_Config.h
 *
 *  Created on: Mar 24, 2024
 *      Author: sakr3
 */

#ifndef MCAL_EXTI_EXTI_CONFIG_H_
#define MCAL_EXTI_EXTI_CONFIG_H_

/* EXTI ENABLE/DISABLE
 * 1- ENABLE
 * 2- DISABLE
 * */

#define EXTI_INT0_ENABLE 	ENABLE
#define EXTI_INT1_ENABLE 	ENABLE
#define EXTI_INT2_ENABLE 	ENABLE

/* EXTI SENSE CONTROL
 * Options :
 * 1- FALLING_EDGE
 * 2- RISSING_EDGE
 * 3- LOW_LEVEL
 * 3- ON_CHANGE
 * */
#define EXTI_INT0_SENSE_CONTROL 	RISSING_EDGE
#define EXTI_INT1_SENSE_CONTROL 	RISSING_EDGE
#define EXTI_INT2_SENSE_CONTROL 	FALLING_EDGE

#endif /* MCAL_EXTI_EXTI_CONFIG_H_ */
